name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create project structure
      run: |
        # Create directories
        mkdir -p app/src/main/java/com/hcr2/capture/net
        mkdir -p app/src/main/res/layout
        mkdir -p app/src/main/res/values
        mkdir -p gradle/wrapper
        
    - name: Create build files
      run: |
        # Create settings.gradle
        echo 'rootProject.name = "SimpleCapture"
        include ":app"' > settings.gradle
        
        # Create top-level build.gradle
        echo 'plugins {
            id "com.android.application" version "8.0.2" apply false
        }
        
        task clean(type: Delete) {
            delete rootProject.buildDir
        }' > build.gradle
        
        # Create app/build.gradle
        echo 'plugins {
            id "com.android.application"
        }
        
        android {
            namespace "com.hcr2.capture"
            compileSdk 33
        
            defaultConfig {
                applicationId "com.hcr2.capture"
                minSdk 24
                targetSdk 33
                versionCode 1
                versionName "1.0"
            }
        
            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
                }
            }
        
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_11
                targetCompatibility JavaVersion.VERSION_11
            }
        }
        
        dependencies {
            implementation "androidx.appcompat:appcompat:1.6.1"
            implementation "com.google.android.material:material:1.9.0"
        }' > app/build.gradle
        
    - name: Download Gradle wrapper
      run: |
        curl -L https://services.gradle.org/distributions/gradle-8.0-bin.zip -o gradle-8.0-bin.zip
        mkdir -p gradle/wrapper
        echo 'distributionBase=GRADLE_USER_HOME
        distributionPath=wrapper/dists
        distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
        zipStoreBase=GRADLE_USER_HOME
        zipStorePath=wrapper/dists' > gradle/wrapper/gradle-wrapper.properties
        curl -L https://raw.githubusercontent.com/gradle/gradle/v8.0.0/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
        echo '#!/usr/bin/env sh
        exec gradle "$@"' > gradlew
        chmod +x gradlew

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
